Repository chonkie-inc/chonkie, pull requests merged in 2025-08, with the labels that each got.

#226 Add `jina-embeddings-v4` + Support for `AzureOpenAIEmbeddings`
  pyproject.toml
  src/chonkie/embeddings/__init__.py
  src/chonkie/embeddings/azure_openai.py
  src/chonkie/embeddings/jina.py
  src/chonkie/embeddings/registry.py
  src/chonkie/genie/azure_openai.py
  tests/embeddings/test_azure_openai_embeddings.py
  tests/embeddings/test_jina_embeddings.py
  tests/genie/test_azure_openai_genie.py
Labels: enhancement

#232 Chore: Bump version to `v1.1.2`
  pyproject.toml
  src/chonkie/__init__.py
Labels: chore

#237 Update README.md — Add recent integrations to the list
  README.md
Labels: documentation

#240 docs: fix url
  docs/python-sdk/getting-started/introduction.mdx
Labels: documentation

#204 Support weaviate
  docs/docs.json
  docs/python-sdk/handshakes/weaviate-handshake.mdx
  pyproject.toml
  src/chonkie/__init__.py
  src/chonkie/friends/__init__.py
  src/chonkie/friends/handshakes/__init__.py
  src/chonkie/friends/handshakes/weaviate.py
  tests/handshakes/test_weaviate_handshake.py
Labels: enhancement

#251 Feat: Add better `SemanticChunker` with peak finding, window similarities and more!
  README.md
  docs/docs.json
  docs/python-sdk/chunkers/sdpm-chunker.mdx
  docs/python-sdk/chunkers/semantic-chunker.mdx
  docs/python-sdk/chunkers/token-chunker.mdx
  pyproject.toml
  setup.py
  src/chonkie/__init__.py
  src/chonkie/chunker/__init__.py
  src/chonkie/chunker/c_extensions/savgol.pyi
  src/chonkie/chunker/c_extensions/savgol.pyx
  src/chonkie/chunker/semantic.py
  src/chonkie/legacy/__init__.py
  src/chonkie/legacy/sdpm.py
  src/chonkie/legacy/semantic.py
  tests/chunkers/test_sdpm_chunker.py
  tests/chunkers/test_semantic_chunker.py
  tests/handshakes/test_mongodb_handshake.py
  uv.lock
Labels: enhancement

#258 Migrate the cookbook to `chonkie-inc/cookbook`
  .github/ISSUE_TEMPLATE/bug_report.md
  cookbook/README.md
  cookbook/examples/gemini_embeddings_with_recursive_chunking.py
  cookbook/examples/pgvector_handshake_with_recursive_chunking.py
  cookbook/examples/recursive_chunker_json_export.py
  cookbook/tutorials/Chonkie_RecursiveChunker_for_PDF_and_Markdown.ipynb
  cookbook/tutorials/Chonkie_SlumberChunker_w_OpenRouter_models.ipynb
Labels: documentation
