Repository chonkie-inc/chonkie, pull requests merged in 2025-05, with the labels that each got.

#91 Add `BaseHandshake` and `BasePorter`
  pyproject.toml
  src/chonkie/__init__.py
  src/chonkie/friends/__init__.py
  src/chonkie/friends/handshakes/__init__.py
  src/chonkie/friends/handshakes/base.py
  src/chonkie/friends/porters/__init__.py
  src/chonkie/friends/porters/base.py
  tests/handshakes/vector_db_writers/test_chroma_handshake.py
  tests/handshakes/vector_db_writers/test_qdrant_handshake.py
  tests/handshakes/vector_db_writers/test_turbopuffer_handshake.py
Labels: enhancement

#92 Update cookbook
  README.md
  assets/chomp-transparent-bg.png
  assets/chomp.png
  cookbook/README.md
Labels: documentation, enhancement

#95 Feat: Add support for `OpenAIGenie` + `TurbopufferHandshake`
  pyproject.toml
  src/chonkie/__init__.py
  src/chonkie/friends/__init__.py
  src/chonkie/friends/handshakes/__init__.py
  src/chonkie/friends/handshakes/turbopuffer.py
  src/chonkie/genie/__init__.py
  src/chonkie/genie/gemini.py
  src/chonkie/genie/openai.py
Labels: enhancement

#82 Feat: Viz: Added a new dark theme, separated the light and the dark themes
  src/chonkie/utils/viz.py
Labels: enhancement

#103 Tutorial: Add example to show `SlumberChunker` with `OpenRouter` models
  cookbook/README.md
  cookbook/tutorials/Chonkie_SlumberChunker_w_OpenRouter_models.ipynb
  src/chonkie/types/document.py
Labels: tutorial

#107 Fix: Linting errors + Add `cloud.SDPMChunker` + `cloud.LateChunker`
  pyproject.toml
  src/chonkie/cloud/__init__.py
  src/chonkie/cloud/chunker/__init__.py
  src/chonkie/cloud/chunker/late.py
  src/chonkie/cloud/chunker/sdpm.py
  src/chonkie/cloud/chunker/semantic.py
  src/chonkie/friends/handshakes/turbopuffer.py
  src/chonkie/types/document.py
  tests/handshakes/test_chroma_handshake.py
  tests/handshakes/test_qdrant_handshake.py
Labels: bug

#108 Feat: Add the `base_url` to the `OpenAIEmbeddings` and `**kwargs` support
  src/chonkie/embeddings/openai.py
Labels: enhancement

#146 Fix: Better `AutoEmbeddings` model matching + URI support for providers
  src/chonkie/embeddings/auto.py
  src/chonkie/embeddings/model2vec.py
  src/chonkie/embeddings/registry.py
Labels: bug, enhancement

#148 Feat: Add `URI` support via `provider://organization/model` style strings in `AutoEmbeddings`
  src/chonkie/embeddings/auto.py
  src/chonkie/embeddings/model2vec.py
  src/chonkie/embeddings/registry.py
Labels: bug, enhancement

#150 Enhance chunker module by adding NeuralChunker and SlumberChunker to the imports and __all__ list for improved functionality.
  src/chonkie/cloud/__init__.py
  src/chonkie/cloud/chunker/__init__.py
  src/chonkie/cloud/chunker/neural.py
  src/chonkie/cloud/chunker/recursive.py
  src/chonkie/cloud/chunker/semantic.py
  src/chonkie/cloud/chunker/sentence.py
  src/chonkie/cloud/chunker/slumber.py
  src/chonkie/cloud/chunker/token.py
  tests/cloud/test_cloud_late_chunker.py
  tests/cloud/test_cloud_neural_chunker.py
  tests/cloud/test_cloud_sdpm_chunker.py
  tests/cloud/test_cloud_slumber_chunker.py
Labels: enhancement

#151 Fix: Add `NeuralChunker` and `SlumberChunker` to the chonkie.cloud
  src/chonkie/cloud/__init__.py
  src/chonkie/cloud/chunker/__init__.py
  src/chonkie/cloud/chunker/neural.py
  src/chonkie/cloud/chunker/recursive.py
  src/chonkie/cloud/chunker/semantic.py
  src/chonkie/cloud/chunker/sentence.py
  src/chonkie/cloud/chunker/slumber.py
  src/chonkie/cloud/chunker/token.py
  tests/cloud/test_cloud_late_chunker.py
  tests/cloud/test_cloud_neural_chunker.py
  tests/cloud/test_cloud_sdpm_chunker.py
  tests/cloud/test_cloud_slumber_chunker.py
Labels: enhancement

#154 Improve test coverage for OverlapRefinery
  src/chonkie/tokenizer.py
  tests/refinery/__init__.py
  tests/refinery/test_overlap_refinery.py
Labels: enhancement

#158 Fix: `CodeChunker` fails multiprocessing due to pickling issues; Run it sequentially
  .gitignore
  src/chonkie/chomp/pipeline.py
  src/chonkie/chunker/code.py
  src/chonkie/chunker/token.py
  src/chonkie/embeddings/jina.py
  src/chonkie/embeddings/model2vec.py
  src/chonkie/embeddings/openai.py
  src/chonkie/embeddings/voyageai.py
  src/chonkie/friends/handshakes/chroma.py
  src/chonkie/friends/handshakes/qdrant.py
  src/chonkie/friends/handshakes/turbopuffer.py
  src/chonkie/genie/gemini.py
  src/chonkie/genie/openai.py
  src/chonkie/tokenizer.py
  src/chonkie/types/base.py
  src/chonkie/types/code.py
  src/chonkie/types/sentence.py
  tests/cloud/test_cloud_code_chunker.py
  tests/cloud/test_cloud_late_chunker.py
  tests/cloud/test_cloud_recursive_chunker.py
  tests/cloud/test_cloud_sdpm_chunker.py
  tests/cloud/test_cloud_semantic_chunker.py
  tests/cloud/test_cloud_slumber_chunker.py
  tests/embeddings/test_cohere_embeddings.py
  tests/embeddings/test_jina_embeddings.py
  tests/embeddings/test_voyageai_embeddings.py
  tests/genie/test_gemini_genie.py
  tests/genie/test_openai_genie.py
  tests/handshakes/test_chroma_handshake.py
  tests/handshakes/test_qdrant_handshake.py
  tests/test_tokenizer.py
Labels: documentation

#167 Update DOCS.md + Add example for `JSONPorter`
  cookbook/README.md
  cookbook/examples/recursive_chunker_json_export.py
  docs/common/pricing.mdx
  src/chonkie/friends/porters/__init__.py
  src/chonkie/friends/porters/json.py
Labels: documentation
